Repository semuconsulting/PyGPSClient, pull requests merged in 2023-03, with the labels that each got.

#43 Rc 1.3.18
  .github/workflows/main.yml
  .gitignore
  .vscode/settings.json
  README.md
  RELEASE_NOTES.md
  colortags
  docs/pygpsclient.rst
  examples/D9S_RXM_PMP.ubx
  examples/device-dummy123-1234-1234-1234-abcdefghijkl-ucenter-config.json
  examples/json-config-load.py
  examples/rxmpmp_extract_spartn.py
  examples/spartn_parser.py
  images/spartn_consolelog.png
  images/spartnconfig_widget.png
  pygpsclient/__main__.py
  pygpsclient/_version.py
  pygpsclient/about_dialog.py
  pygpsclient/app.py
  pygpsclient/banner_frame.py
  pygpsclient/console_frame.py
  pygpsclient/file_handler.py
  pygpsclient/globals.py
  pygpsclient/gpx_dialog.py
  pygpsclient/helpers.py
  pygpsclient/map_frame.py
  pygpsclient/mqtt_handler.py
  pygpsclient/settings_frame.py
  pygpsclient/spartn_dialog.py
  pygpsclient/spartn_gnss_frame.py
  pygpsclient/spartn_json_config.py
  pygpsclient/spartn_lband_frame.py
  pygpsclient/spartn_mqtt_frame.py
  pygpsclient/spartnmessage.py
  pygpsclient/spectrum_frame.py
  pygpsclient/stream_handler.py
  pygpsclient/strings.py
  pygpsclient/ubx_dynamic_frame.py
  pygpsclient/ubx_handler.py
  requirements.txt
  setup.py
  snapcraft.yaml
  tests/test_spartn_stream.py
Labels: bug, documentation, enhancement

#49 Add D9S save config facility Fixes #48
  README.md
  images/spartnconfig_widget.png
  pygpsclient/spartn_lband_frame.py
Labels: enhancement

#50 Rc1.3.19
  .github/ISSUE_TEMPLATE/bug_report.md
  .vscode/settings.json
  CONTRIBUTING.md
  RELEASE_NOTES.md
  examples/json-config-load.py
  examples/socket_server.py
  examples/spartn_parser.py
  examples/tcpserver_threaded.py
  pygpsclient/_version.py
  pygpsclient/banner_frame.py
  pygpsclient/strings.py
  requirements.txt
  setup.py
Labels: bug, enhancement

#52 Add a scatterplot view.
  README.md
  pygpsclient/app.py
  pygpsclient/globals.py
  pygpsclient/menu_bar.py
  pygpsclient/scatter_frame.py
  pygpsclient/serialconfig_frame.py
  pygpsclient/strings.py
  setup.py
Labels: enhancement

#54 Refine widget positioning
  .vscode/settings.json
  .vscode/tasks.json
  RELEASE_NOTES.md
  pyproject.toml
  src/pygpsclient/_version.py
  src/pygpsclient/app.py
  src/pygpsclient/globals.py
  src/pygpsclient/scatter_frame.py
  src/pygpsclient/skyview_frame.py
Labels: enhancement

#55 Update test framework
  .coveragerc
  .github/pull_request_template.md
  .github/workflows/main.yml
  .vscode/settings.json
  .vscode/tasks.json
  CONTRIBUTING.md
  pyproject.toml
  tests/test_static.py
Labels: enhancement
